spring:
  application:
    name: service-maintenance
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

web:
  message: Welcome to WeB Fleet Service/Maintenance

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:hsqldb:mem:testdb
