apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: service-maintenance
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: service-maintenance
    apps.tanzu.vmware.com/has-tests: true
spec:
#  env:
#    - name: JAVA_TOOL_OPTIONS
#      value: "-XX:MaxMetaspaceSize=131072K"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: mysql
    ref:
      apiVersion: with.sql.tanzu.vmware.com/v1
      kind: MySQL
      name: mysql-webfleet
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-1
  source:
    git:
      url: https://github.com/bkieling/service-maintenance.git
      ref:
        branch: main
