apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: service-maintenance
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: service-maintenance
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://gitlab.eng.vmware.com/web-fleet-practice/service-maintenance.git
      ref:
        branch: main
